### ISSUE TITLE
Building Deficiencies at Gun Store

### ISSUE THREAD

**Issue by exxisted** [jackTabsCode/broadview-issues#3]
Weird part mishap on front:
![871ac82a6f465de76bfc8562066ea859](https://user-images.githubusercontent.com/47222108/125200239-2616b380-e238-11eb-9f9a-7b7816ab27f5.png)

Part clipping through window:
![baad723cad0c6e4ab7cf09d49759b921](https://user-images.githubusercontent.com/47222108/125200246-375fc000-e238-11eb-866c-b42cbfa9ea3d.png)

**Comment by exxisted** [comment]
Note: first deficiency is on all of them across the map
![a643642f186f8bf45084f26653264aa0](https://user-images.githubusercontent.com/47222108/125200324-8c9bd180-e238-11eb-98aa-ccf23456d73d.png)

**Comment by jackTabsCode** [comment]
I don't plan on spending time fixing it rn as you have to look at a certain angle
