### ISSUE TITLE
Can't Load Into Game

### ISSUE THREAD

**Issue by DarkShadow101AB** [jackTabsCode/broadview-issues#7]
I recall being on team before the BCSO reform and now when I go to hop on game, it only provides me the Leesburg station option to spawn at. After clicking space, I get this black screen that doesn't go away.

Medal Clip: https://medal.tv/clips/68715362/d1337iI0cYSN?invite=cr-MSwxM0gsOTkwNTkwNiw
F9 Console displayed in the end.

**Comment by jackTabsCode** [comment]
Should be resolved.
