### ISSUE TITLE
Closing Shop GUI Results in Wrong Purchase

### ISSUE THREAD

**Issue by exxisted** [jackTabsCode/broadview-issues#9]
If you open a shop GUI and use the arrows to navigate to a new item, close the shop GUI, and then re-open it, the following happens:
[https://gyazo.com/697d8440676934e4044ddf20f2b6d403](https://gyazo.com/697d8440676934e4044ddf20f2b6d403)

Basically, it re-opens to the item you are on, but when you buy it, you buy the first item in the shop.

**Comment by jackTabsCode** [comment]
Thank you! Fixed!
